package com.ewos.offer.domain.events;

/** Offer + pre-boarding lifecycle event codes published on {@code ewos.offer.event}. */
public enum OfferEventType {
    OFFER_TEMPLATE_CREATED,
    OFFER_TEMPLATE_UPDATED,
    OFFER_TEMPLATE_DEACTIVATED,
    OFFER_DRAFTED,
    OFFER_SUBMITTED,
    OFFER_APPROVED,
    OFFER_REJECTED,
    OFFER_EXTENDED,
    OFFER_ACCEPTED,
    OFFER_DECLINED,
    OFFER_REVISED,
    OFFER_EXPIRED,
    OFFER_WITHDRAWN,
    OFFER_NEGOTIATION_LOGGED,
    PREBOARDING_CHECKLIST_CREATED,
    PREBOARDING_TASK_CREATED,
    PREBOARDING_TASK_STARTED,
    PREBOARDING_TASK_COMPLETED,
    PREBOARDING_TASK_SKIPPED,
    PREBOARDING_TASK_FAILED,
    PREBOARDING_CHECKLIST_COMPLETED,
    PREBOARDING_CHECKLIST_JOINED,
    PREBOARDING_CHECKLIST_CANCELLED,
    PREBOARDING_CHECKLIST_NO_SHOW
}
