package com.ewos.learning.domain.events;

/** Learning lifecycle event codes published on {@code ewos.learning.event}. */
public enum LearningEventType {
    COURSE_CREATED,
    COURSE_UPDATED,
    COURSE_DEACTIVATED,
    PATH_CREATED,
    PATH_UPDATED,
    PATH_COURSE_ADDED,
    SESSION_SCHEDULED,
    SESSION_STARTED,
    SESSION_COMPLETED,
    SESSION_CANCELLED,
    ENROLLMENT_NOMINATED,
    ENROLLMENT_ENROLLED,
    ENROLLMENT_STARTED,
    ENROLLMENT_ATTENDANCE_RECORDED,
    ENROLLMENT_ASSESSMENT_RECORDED,
    ENROLLMENT_COMPLETED,
    ENROLLMENT_FAILED,
    ENROLLMENT_WITHDRAWN,
    ENROLLMENT_NO_SHOW,
    CERTIFICATION_ISSUED,
    CERTIFICATION_REVOKED,
    CERTIFICATION_EXPIRED
}
