package com.ewos.performance.domain.events;

/** Performance lifecycle event codes published on {@code ewos.performance.event}. */
public enum PerformanceEventType {
    CYCLE_CREATED,
    CYCLE_OPENED,
    CYCLE_ADVANCED,
    CYCLE_CLOSED,
    CYCLE_CANCELLED,
    TEMPLATE_CREATED,
    TEMPLATE_UPDATED,
    TEMPLATE_DEACTIVATED,
    APPRAISAL_OPENED,
    SELF_ASSESSMENT_SUBMITTED,
    MANAGER_ASSESSMENT_SUBMITTED,
    REVIEWER_ASSESSMENT_SUBMITTED,
    CALIBRATION_RECORDED,
    APPRAISAL_SUBMITTED_FOR_APPROVAL,
    APPRAISAL_APPROVED,
    APPRAISAL_REJECTED,
    APPRAISAL_FINALISED,
    APPRAISAL_CANCELLED,
    INCREMENT_RECOMMENDED,
    PROMOTION_RECOMMENDED,
    CALIBRATION_SESSION_CREATED,
    CALIBRATION_SESSION_COMPLETED
}
