package com.ewos.ats.domain.events;

/** ATS lifecycle event codes published on {@code ewos.ats.event}. */
public enum AtsEventType {
    CANDIDATE_CREATED,
    CANDIDATE_UPDATED,
    CANDIDATE_STATUS_CHANGED,
    CANDIDATE_ARCHIVED,
    CANDIDATE_BLACKLISTED,
    CANDIDATE_TAGGED,
    CANDIDATE_UNTAGGED,
    RESUME_UPLOADED,
    RESUME_PARSED,
    RESUME_MARKED_PRIMARY,
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    NOTE_ADDED,
    COMMUNICATION_LOGGED,
    APPLICATION_CREATED,
    APPLICATION_STATUS_CHANGED,
    APPLICATION_REJECTED,
    APPLICATION_WITHDRAWN,
    APPLICATION_ON_HOLD,
    APPLICATION_RESUMED,
    APPLICATION_HIRED,
    APPLICATION_OFFER_EXTENDED,
    APPLICATION_OFFER_ACCEPTED,
    APPLICATION_OFFER_DECLINED
}
