package com.ewos.ats.domain;

/** Append-only event codes for {@link CandidateTimelineEvent}. */
public enum TimelineEventType {
    CANDIDATE_CREATED,
    CANDIDATE_UPDATED,
    CANDIDATE_STATUS_CHANGED,
    CANDIDATE_TAGGED,
    CANDIDATE_UNTAGGED,
    RESUME_UPLOADED,
    RESUME_MARKED_PRIMARY,
    RESUME_PARSED,
    DOCUMENT_UPLOADED,
    NOTE_ADDED,
    COMMUNICATION_LOGGED,
    APPLICATION_CREATED,
    APPLICATION_STATUS_CHANGED,
    APPLICATION_REJECTED,
    APPLICATION_WITHDRAWN,
    APPLICATION_HIRED
}
